#!/bin/bash
echo "🔍 Vérification du domaine windventure.fr..."
echo "=========================================="
echo ""
echo "1. Résolution DNS:"
nslookup windventure.fr 2>/dev/null || echo "DNS pas encore propagé"
echo ""
echo "2. Test HTTPS:"
curl -I -s https://windventure.fr | head -n 1 || echo "Site pas encore accessible"
echo ""
echo "3. Certificat SSL:"
echo | openssl s_client -connect windventure.fr:443 2>/dev/null | openssl x509 -noout -dates 2>/dev/null || echo "SSL pas encore actif"
echo ""
echo "=========================================="
echo "⏱️  Si pas encore actif, réessayez dans 15-30 min"
