#!/usr/bin/env node

/**
 * 🔑 WINDVENTURE STRIPE SETUP ASSISTANT
 * Script interactif pour configurer les clés Stripe
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function askQuestion(question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

async function setupStripe() {
  console.log('\n🚀 WINDVENTURE STRIPE CONFIGURATION ASSISTANT');
  console.log('='.repeat(60));
  console.log('Ce script va vous aider à configurer vos clés Stripe.\n');

  // Check if .env.local already exists
  const envPath = path.join(process.cwd(), '.env.local');
  const envExists = fs.existsSync(envPath);
  
  if (envExists) {
    const overwrite = await askQuestion('⚠️  .env.local existe déjà. Voulez-vous le remplacer? (y/n): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('❌ Configuration annulée.');
      rl.close();
      return;
    }
  }

  console.log('\n📋 ÉTAPE 1: TYPE D\'ENVIRONNEMENT');
  console.log('1. Development (clés test)');  
  console.log('2. Production (clés live)');
  const envType = await askQuestion('Choisissez votre environnement (1 ou 2): ');
  
  const isProduction = envType === '2';
  const keyPrefix = isProduction ? 'live' : 'test';
  
  console.log(`\n🔑 ÉTAPE 2: CLÉS STRIPE ${keyPrefix.toUpperCase()}`);
  console.log(`Récupérez vos clés depuis: https://dashboard.stripe.com/apikeys`);
  
  const publishableKey = await askQuestion(`Publishable Key (pk_${keyPrefix}_...): `);
  if (!publishableKey.startsWith(`pk_${keyPrefix}_`)) {
    console.log(`❌ Erreur: La clé doit commencer par pk_${keyPrefix}_`);
    rl.close();
    return;
  }
  
  const secretKey = await askQuestion(`Secret Key (sk_${keyPrefix}_...): `);
  if (!secretKey.startsWith(`sk_${keyPrefix}_`)) {
    console.log(`❌ Erreur: La clé doit commencer par sk_${keyPrefix}_`);
    rl.close();
    return;
  }

  console.log('\n🔗 ÉTAPE 3: WEBHOOK SECRET');
  console.log('Créez un webhook sur: https://dashboard.stripe.com/webhooks');
  console.log('URL: https://windventure-premium.vercel.app/api/stripe-webhook');
  
  const webhookSecret = await askQuestion('Webhook Signing Secret (whsec_...): ');
  if (!webhookSecret.startsWith('whsec_')) {
    console.log('❌ Erreur: Le secret doit commencer par whsec_');
    rl.close();
    return;
  }

  console.log('\n🌐 ÉTAPE 4: URL DE BASE');
  const defaultUrl = isProduction ? 'https://windventure-premium.vercel.app' : 'http://localhost:3000';
  const baseUrl = await askQuestion(`Base URL (défaut: ${defaultUrl}): `) || defaultUrl;

  // Generate .env.local content
  const envContent = `# 🔐 WINDVENTURE STRIPE CONFIGURATION
# Generated by setup-stripe.js on ${new Date().toISOString()}

# 🌐 BASE URL
NEXT_PUBLIC_BASE_URL=${baseUrl}

# 💳 STRIPE CONFIGURATION (${keyPrefix.toUpperCase()} KEYS)
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${publishableKey}
STRIPE_SECRET_KEY=${secretKey}
STRIPE_WEBHOOK_SECRET=${webhookSecret}

# 🏷️ STRIPE PRODUCT IDS (pré-configurés)
STRIPE_BEGINNER_PRIVATE_PRICE=price_1Reo9xHUqGxCezEFwTKoXkzJ
STRIPE_BEGINNER_SEMI_PRIVATE_PRICE=price_1Reo8SHUqGxCezEF3ca4QL34
STRIPE_EXPLORATION_PRICE=price_1ReoC9HUqGxCezEFSDRUrGTz
STRIPE_COMBINED_PRICE=price_1ReoApHUqGxCezEFCuWVKKGB

# 📧 EMAIL CONFIGURATION (optionnel)
# RESEND_API_KEY=your_resend_key_here
# FROM_EMAIL=booking@windventure.fr
# ADMIN_EMAIL=hamzaseidou582@gmail.com

# 🚀 ENVIRONMENT
NODE_ENV=${isProduction ? 'production' : 'development'}

# ⚠️ SÉCURITÉ
# Ne jamais committer ce fichier dans Git
# Garder ces clés secrètes et sécurisées
`;

  // Write .env.local file
  fs.writeFileSync(envPath, envContent);

  console.log('\n✅ CONFIGURATION TERMINÉE!');
  console.log('='.repeat(40));
  console.log(`📁 Fichier créé: .env.local`);
  console.log(`🔑 Type de clés: ${keyPrefix.toUpperCase()}`);
  console.log(`🌐 URL de base: ${baseUrl}`);
  
  console.log('\n📋 PROCHAINES ÉTAPES:');
  console.log('1. ✅ Configuration locale terminée');
  console.log('2. 🚀 Démarrer: npm run dev');
  console.log('3. 🧪 Tester: http://localhost:3000/book?package=combined');
  
  if (isProduction) {
    console.log('4. ☁️  Configurer variables Vercel:');
    console.log('   vercel env add NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY');
    console.log('   vercel env add STRIPE_SECRET_KEY');
    console.log('   vercel env add STRIPE_WEBHOOK_SECRET');
    console.log('5. 🚀 Déployer: vercel --prod');
  }

  console.log('\n🎉 WINDVENTURE STRIPE EST MAINTENANT CONFIGURÉ!');
  rl.close();
}

// Run the setup
setupStripe().catch(console.error);